### ISSUE TITLE
Send image from ROS2 to Fastrtps

### ISSUE THREAD

**Issue by golizheh** [eProsima/SOSS-DDS#25]
Hi, 
I have create image.idl file and by using fastrtpsgen generate files.
Image.id

It is look like the type: "sensor_msgs/Image" is not defined and soss is not working.

Thanks and look forward to hearing from you

**Comment by LuisGP** [comment]
Hi @golizheh 

I'd need to take a look into your `myfile.yaml` file to find out which can be the problem.
In any case, I don't understand what do you mean with `How can I show image`.

**Comment by golizheh** [comment]
Hi @LuisGP 

Myfile.yaml is as follow:

```yaml
systems:
    dds:
      type: dds
      dynamic types:
        struct std_msgs__String:
          string: "data"

    ros2:
      type: ros2

routes:
    ros2_to_dds: { from: ros2, to: dds }
    dds_to_ros2: { from: dds, to: ros2 }

topics:
    hello_ros2: { type: "std_msgs/String", route: dds_to_ros2 }
    image: { type: "sensor_msgs/Image", route: ros2_to_dds } 
```

When I run it I will get following error:
```bash
soss-ros2 could not find .mix file for message type: sensor_msgs/Image
```

> "In any case, I don't understand what do you mean with How can I show image."

I mean it is look like subscriber is mached, but can not show any information, How can I show my image, is it in the following function:

```cpp
void ImageSubscriber::SubListener::onNewDataMessage(Subscriber* sub)
```

I have test it is here but I can not get any data ?  how subscriber can show data as image?
what kind of changes is needed to the subscriber class to be sure if it is get image and can show it?

Thanks in advance

**Comment by LuisGP** [comment]
Hi @golizheh 

Your `myfile.yaml` is describing the following situation:

`DDS` -> `std_msgs__String` -> SOSS -> `std_msgs__String` -> `ROS2`
`ROS2` -> `sensor_msgs__Image` -> SOSS -> `sensor_msgs__Image` -> `DDS`

Is that correct?

Your type `Image` must be generated to be used by [ROS2](https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/) too.

Once you are called to the `onNewDataMessage` you must retrieve the associated data to the change:

```cpp
[...]
Image data;
sub->takeNextData(&data, &sample_info);
[...]
```

You can see a complete example in the [HelloWorld](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample) example in Fast-RTPS.

If you are not being called to the `onNewDataMessage` function, that means the application isn't being able to receive or decode the received data. Very likely because the publisher (the SOSS-DDS system handler in this case) isn't publishing anything, as it doesn't receive data from the misconfigured ROS2 publisher.

`ROS2` -X-> `sensor_msgs__Image` -> SOSS -> `sensor_msgs__Image` -> `DDS`

**Comment by golizheh** [comment]
ROS2 -> sensor_msgs__Image -> SOSS -> sensor_msgs__Image -> DDS (Yes this is correct, I just want to have a one way communication from ROS2 to DDS).

"Your type Image must be generated to be used by ROS2 too. " How can I do that? In order to dont get error when I run soss myfile.yaml

**Comment by LuisGP** [comment]
In your scenario, all involved entities talk the same type, but each entity must define that type on their own.

In Fast-RTPS, you already have it by using your `image.idl` and `fastrtpsgen`.
In ROS2, you must define it again, for example adding the following snippet to your `CMakeLists.txt`:

```cmake
rosidl_generate_interfaces(image_msg  "msg/image.msg"  DEPENDENCIES builtin_interfaces)
```

To create the `image.msg` file, follow the ROS2 tutorials, like [this](https://www.theconstructsim.com/ros2-tutorials-7-how-to-create-a-ros2-custom-message-new/), and the ROS2 documentation, [here](https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/).

Finally, `SOSS-DDS` needs the type too. Unfortunately, there is no automatic conversion from `msg` or `idl` files yet, so you must define it again using the `yaml` file itself.
As you only want to have that data flow, you must modify the `myfile.yaml` as follows:

```yaml
systems:
    dds:
      type: dds
      dynamic types:
        struct sensor_msgs__Image:
          [...] # Here your Image type in yaml format. 

    ros2:
      type: ros2

routes:
    ros2_to_dds: { from: ros2, to: dds }

topics:
    image: { type: "sensor_msgs__Image", route: ros2_to_dds } 
```

There is no documentation about the `dynamic types` syntax yet, but you can take a look at examples and tests, like [here](https://github.com/eProsima/SOSS-DDS/blob/master/dds/sample/complex_types_tst.yaml).
